# Generated by Django 4.2.3 on 2023-07-24 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_britanniatarget_app_eco_retention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='britanniatarget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='britanniatarget',
            name='year',
        ),
        migrations.AddField(
            model_name='britanniatarget',
            name='britannia_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.britanniaprogram'),
        ),
        migrations.AddField(
            model_name='britanniatarget',
            name='britannia_program_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='britanniatarget',
            name='inserted_by_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='retailerpayout',
            name='britannia_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.britanniaprogram'),
        ),
        migrations.AddField(
            model_name='retailerpayout',
            name='britannia_program_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='retailerpayout',
            name='inserted_by',
            field=models.CharField(blank=True, help_text='Inserted By', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='retailerpayout',
            name='inserted_by_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='BritanniaTargetYearMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('britannia_program_name', models.CharField(blank=True, max_length=30, null=True)),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('inserted_by', models.CharField(blank=True, help_text='Inserted By', max_length=15, null=True)),
                ('inserted_by_role', models.CharField(blank=True, max_length=30, null=True)),
                ('britannia_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.britanniaprogram')),
            ],
        ),
        migrations.AddField(
            model_name='britanniatarget',
            name='britannia_target_year_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.britanniatargetyearmaster'),
        ),
    ]
