# Generated by Django 4.2.3 on 2023-07-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_britanniatarget_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BritanniaPointYearMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('inserted_by', models.CharField(blank=True, help_text='Inserted By', max_length=15, null=True)),
                ('inserted_by_role', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'accounts_britannia_point_year_master',
            },
        ),
        migrations.AddField(
            model_name='britanniapoint',
            name='bpu_remark',
            field=models.CharField(blank=True, help_text='BPU Remark', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='britanniapoint',
            name='month',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='britanniapoint',
            name='year',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='britanniapoint',
            name='britannia_point_year_master',
            field=models.ForeignKey(blank=True, help_text='Britannia Point Year Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.britanniapointyearmaster'),
        ),
    ]
