# Generated by Django 4.2.3 on 2023-07-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_britanniapoint_britannia_program_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='britanniapointyearmaster',
            old_name='inserted_by_role',
            new_name='login_role',
        ),
        migrations.RenameField(
            model_name='britanniapointyearmaster',
            old_name='inserted_by',
            new_name='login_user',
        ),
        migrations.RenameField(
            model_name='britanniatargetyearmaster',
            old_name='inserted_by_role',
            new_name='login_role',
        ),
        migrations.RenameField(
            model_name='britanniatargetyearmaster',
            old_name='inserted_by',
            new_name='login_user',
        ),
        migrations.RenameField(
            model_name='retailerpayout',
            old_name='inserted_by_role',
            new_name='login_role',
        ),
        migrations.RenameField(
            model_name='retailerpayout',
            old_name='inserted_by',
            new_name='login_user',
        ),
        migrations.AddField(
            model_name='britanniadate',
            name='login_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='britanniadate',
            name='login_user',
            field=models.CharField(blank=True, help_text='Inserted By', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='britanniapoint',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='britanniaurl',
            name='login_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='britanniaurl',
            name='login_user',
            field=models.CharField(blank=True, help_text='Inserted By', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='retailerpayout',
            name='exception',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='retailerpayout',
            name='po',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='retailerpayout',
            name='regular',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='login_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='login_user',
            field=models.CharField(blank=True, help_text='Inserted By', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='login_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='login_user',
            field=models.CharField(blank=True, help_text='Inserted By', max_length=15, null=True),
        ),
    ]
