# Generated by Django 4.2.3 on 2023-07-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_inserted_by_role_britanniapointyearmaster_login_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='britanniadate',
            name='britannia_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.britanniaprogram'),
        ),
        migrations.AddField(
            model_name='britanniadate',
            name='britannia_program_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
