# Generated by Django 4.2.3 on 2023-07-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_britanniadate_britannia_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='overall_mtd_in_lakh',
        ),
        migrations.AddField(
            model_name='retailerpayout',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='overall_mtd',
            field=models.CharField(blank=True, help_text='In lakhs', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='BritanniaSaleYearMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('britannia_program_name', models.CharField(blank=True, max_length=30, null=True)),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('login_user', models.CharField(blank=True, help_text='Inserted By', max_length=15, null=True)),
                ('login_role', models.CharField(blank=True, max_length=30, null=True)),
                ('britannia_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.britanniaprogram')),
            ],
        ),
        migrations.AddField(
            model_name='salesdata',
            name='britannia_sale_year_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.britanniasaleyearmaster'),
        ),
    ]
