# Generated by Django 4.2.3 on 2023-07-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_salesdata_overall_mtd_in_lakh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='britanniaurl',
            name='britannia_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.britanniaprogram'),
        ),
        migrations.AddField(
            model_name='britanniaurl',
            name='britannia_program_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='ghee',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
