# Generated by Django 4.2.3 on 2023-07-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_britanniaurl_britannia_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='britanniasaleyearmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='britanniasaleyearmaster',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='BritanniaPayoutYearMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('britannia_program_name', models.CharField(blank=True, max_length=30, null=True)),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('login_user', models.CharField(blank=True, help_text='Inserted By', max_length=15, null=True)),
                ('login_role', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('britannia_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.britanniaprogram')),
            ],
        ),
        migrations.AddField(
            model_name='retailerpayout',
            name='britannia_payout_year_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.britanniapayoutyearmaster'),
        ),
    ]
