# Generated by Django 4.2.3 on 2023-07-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_britanniasaleyearmaster_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='britanniapointyearmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='britanniapointyearmaster',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='britanniatargetyearmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='britanniatargetyearmaster',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
