# Generated by Django 4.2.3 on 2023-08-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_britanniapointyearmaster_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ase_user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='inserted_date',
        ),
        migrations.AlterModelTable(
            name='britanniapointyearmaster',
            table=None,
        ),
    ]
